### ISSUE TITLE
MapboxCoreNavigationTests.testJumpAheadToLastStep fails – RouterException Route Unknown Error

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#3872]
[This build](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/8088/workflows/2f875c15-1b80-4b7f-818e-1e7229c05cc0/jobs/69856) consistently fails with the following error:

```
2022-05-07 01:15:14.568030+0000 xctest[3222:81360] [Mapbox] [Info, nav-native]: RouteAlternativesControllerImpl::setRoutes alternatives=[ 1 2 ], removed=[ ]
2022-05-07 01:15:14.684274+0000 xctest[3222:81360] [Mapbox] [Info, nav-native]: Onboard router: Get route request: https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-122.412755,37.792997%3B-122.433378,37.772701?alternatives=true&continue_straight=true&roundabout_exits=true&enable_refresh=true&avoid_maneuver_radius=623.211&geometries=polyline6&overview=full&steps=true&language=en-US&voice_instructions=true&voice_units=imperial&banner_instructions=true&bearings=170.859,90.0;&annotations=duration,maxspeed,congestion_numeric&access_token=****Bede
2022-05-07 01:15:14.693358+0000 xctest[3222:81360] [Mapbox] [Warning, valhalla]: No metadata found for tiles
2022-05-07 01:15:15.639997+0000 xctest[3222:81360] [Mapbox] [Error, nav-native]: getRoute("https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-122.412755,37.792997%3B-122.433378,37.772701?alternatives=true&continue_straight=true&roundabout_exits=true&enable_refresh=true&avoid_maneuver_radius=623.211&geometries=polyline6&overview=full&steps=true&language=en-US&voice_instructions=true&voice_units=imperial&banner_instructions=true&bearings=170.859,90.0;&annotations=duration,maxspeed,congestion_numeric&access_token=pk.feedCafeDadeDeadBeef-BadeBede.FadeCafeDadeDeed-BadeBede") failed: RouterException Route Unknown Error
/Users/distiller/project/Tests/MapboxCoreNavigationTests/MapboxCoreNavigationTests.swift:209: error: -[MapboxCoreNavigationTests.MapboxCoreNavigationTests testJumpAheadToLastStep] : Asynchronous wait failed: Exceeded timeout of 5 seconds, with unfulfilled expectations: "Expect notification 'RouteControllerDidPassSpokenInstructionPoint' from <MapboxCoreNavigation.RouteController: 0x7fef856a0120>".
```

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
This started failing on main after #3754 was merged.

**Comment by 1ec5** [comment]
Oddly, I can’t reproduce this failure locally at all. It does seem to be slightly nondeterministic, affecting a different build job in different PRs.

**Comment by 1ec5** [comment]
I can occasionally reproduce this issue locally, but it reproduces more reliably on CI given the number of build jobs per commit or push.

The request URLs in all these error messages are valid. The Mapbox Directions API returns responses for these requests successfully.

In 7b3c0b61d9b34f8a163705040a9bebd05bb6cfea, where I increased the timeout to 7&nbsp;seconds, I typically got the same rate of failure with the same unknown error. However, one time I got [more error messages from the router](https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/8091/workflows/881620a9-939f-460d-80a1-0ad9e3062a16/jobs/69888):

```
2022-05-07 04:10:45.944240+0000 xctest[3833:16540] [Mapbox] [Info, nav-native]: RouteAlternativesControllerImpl::setRoutes alternatives=[ 1 2 ], removed=[ ]
2022-05-07 04:10:46.005144+0000 xctest[3833:16539] [Mapbox] [Info, nav-native]: Onboard router: Get route request: https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-122.412755,37.792997%3B-122.433378,37.772701?alternatives=true&continue_straight=true&roundabout_exits=true&enable_refresh=true&avoid_maneuver_radius=622.137&geometries=polyline6&overview=full&steps=true&language=en-US&voice_instructions=true&voice_units=imperial&banner_instructions=true&bearings=170.859,90.0;&annotations=duration,maxspeed,congestion_numeric&access_token=****Bede
2022-05-07 04:10:46.012238+0000 xctest[3833:16539] [Mapbox] [Warning, valhalla]: No metadata found for tiles
2022-05-07 04:10:46.594165+0000 xctest[3833:16539] [Mapbox] [Error, nav-native]: getRoute("https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-122.412755,37.792997%3B-122.433378,37.772701?alternatives=true&continue_straight=true&roundabout_exits=true&enable_refresh=true&avoid_maneuver_radius=622.137&geometries=polyline6&overview=full&steps=true&language=en-US&voice_instructions=true&voice_units=imperial&banner_instructions=true&bearings=170.859,90.0;&annotations=duration,maxspeed,congestion_numeric&access_token=pk.feedCafeDadeDeadBeef-BadeBede.FadeCafeDadeDeed-BadeBede") failed: RouterException No suitable edges near location
2022-05-07 04:10:46.629737+0000 xctest[3833:16540] [Mapbox] [Info, nav-native]: Onboard router: Get route request: https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-122.422431,37.774091%3B-122.433378,37.772701?alternatives=true&continue_straight=true&roundabout_exits=true&enable_refresh=true&avoid_maneuver_radius=470.112&geometries=polyline6&overview=full&steps=true&language=en-US&voice_instructions=true&voice_units=imperial&banner_instructions=true&bearings=260.778,90.0;&annotations=duration,maxspeed,congestion_numeric&access_token=****Bede
2022-05-07 04:10:46.636825+0000 xctest[3833:16540] [Mapbox] [Warning, valhalla]: No metadata found for tiles
2022-05-07 04:10:46.639493+0000 xctest[3833:16540] [Mapbox] [Error, nav-native]: getRoute("https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-122.422431,37.774091%3B-122.433378,37.772701?alternatives=true&continue_straight=true&roundabout_exits=true&enable_refresh=true&avoid_maneuver_radius=470.112&geometries=polyline6&overview=full&steps=true&language=en-US&voice_instructions=true&voice_units=imperial&banner_instructions=true&bearings=260.778,90.0;&annotations=duration,maxspeed,congestion_numeric&access_token=pk.feedCafeDadeDeadBeef-BadeBede.FadeCafeDadeDeed-BadeBede") failed: RouterException No suitable edges near location
2022-05-07 04:10:46.652413+0000 xctest[3833:16538] [Mapbox] [Info, nav-native]: Onboard router: Get route request: https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-122.423815,37.773915%3B-122.433378,37.772701?alternatives=true&continue_straight=true&roundabout_exits=true&enable_refresh=true&avoid_maneuver_radius=719.724&geometries=polyline6&overview=full&steps=true&language=en-US&voice_instructions=true&voice_units=imperial&banner_instructions=true&bearings=260.67,90.0;&annotations=duration,maxspeed,congestion_numeric&access_token=****Bede
2022-05-07 04:10:46.659285+0000 xctest[3833:16538] [Mapbox] [Warning, valhalla]: No metadata found for tiles
2022-05-07 04:10:46.661776+0000 xctest[3833:16538] [Mapbox] [Error, nav-native]: getRoute("https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-122.423815,37.773915%3B-122.433378,37.772701?alternatives=true&continue_straight=true&roundabout_exits=true&enable_refresh=true&avoid_maneuver_radius=719.724&geometries=polyline6&overview=full&steps=true&language=en-US&voice_instructions=true&voice_units=imperial&banner_instructions=true&bearings=260.67,90.0;&annotations=duration,maxspeed,congestion_numeric&access_token=pk.feedCafeDadeDeadBeef-BadeBede.FadeCafeDadeDeed-BadeBede") failed: RouterException No suitable edges near location
2022-05-07 04:10:46.800878+0000 xctest[3833:16538] [Mapbox] [Info, nav-native]: Onboard router: Get route request: https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-122.433378,37.772701%3B-122.433378,37.772701?alternatives=true&continue_straight=true&roundabout_exits=true&enable_refresh=true&avoid_maneuver_radius=1000.0&geometries=polyline6&overview=full&steps=true&language=en-US&voice_instructions=true&voice_units=imperial&banner_instructions=true&bearings=260.883,90.0;&annotations=duration,maxspeed,congestion_numeric&access_token=****Bede
2022-05-07 04:10:46.815892+0000 xctest[3833:16538] [Mapbox] [Warning, valhalla]: No metadata found for tiles
2022-05-07 04:10:46.831025+0000 xctest[3833:16538] [Mapbox] [Error, nav-native]: getRoute("https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-122.433378,37.772701%3B-122.433378,37.772701?alternatives=true&continue_straight=true&roundabout_exits=true&enable_refresh=true&avoid_maneuver_radius=1000.0&geometries=polyline6&overview=full&steps=true&language=en-US&voice_instructions=true&voice_units=imperial&banner_instructions=true&bearings=260.883,90.0;&annotations=duration,maxspeed,congestion_numeric&access_token=pk.feedCafeDadeDeadBeef-BadeBede.FadeCafeDadeDeed-BadeBede") failed: RouterException No suitable edges near location
```

This suggests the tiles haven’t been downloaded completely. How do the tests ensure that the tiles are available upfront?

**Comment by Udumft** [comment]
I can't see what makes this particular test different. There are other, very similar tests in `MapboxCoreNavigationTests` which do the same route or it's portions, and not failing. I could guess that it takes some time to download tiles, and `testJumpAheadToLastStep` is the first one to run, so it hits the timeout, but it is not the case as it is run somewhere in the middle.
Just a guess: if you've managed to reproduce it locally, could you try to use `MapboxRoutingProvider(.hybrid)` or `customRoutingProvider: nil` on this one to see if it makes any difference?

**Comment by Udumft** [comment]
I also noticed that navigation service in `MapboxCoreNavigationTests.swift` starts a test with an instant reroute attempt. I am not sure why it happens and if it has effect on the tests, but those `getRoute` errors are coming from a reroute, which is not meant to happen in these tests.

**Comment by Udumft** [comment]
I've managed to mitigate this issue (see related [PR](https://github.com/mapbox/mapbox-navigation-ios/pull/3884)). If found that there are some unexpected reroutes occur which seems to interfere with tests flow. It also seems that reroute is issued instantly after starting the navigation, ignoring the designed reroute detected -> reroute approved/denied, which could be a bug. I'll investigate it further.
